# Generated by Django 5.0.4 on 2024-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название группы'),
        ),
    ]
