# Generated by Django 5.0.4 on 2024-04-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=150, verbose_name='Название заметки')),
                ('note_text', models.TextField(max_length=9999999, verbose_name='Текст заметки')),
                ('note_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('note_refresh_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения заметки')),
                ('completion_status_tag', models.CharField(blank=True, choices=[('seen', 'Просмотрено'), ('in_progress', 'Принято в работу'), ('completed', 'Завершено')], null=True, verbose_name='Статус завершения')),
                ('importance_status_tag', models.CharField(blank=True, choices=[('low', 'Может подождать'), ('medium', 'В порядке очереди'), ('high', 'Требуется немедленное вмешательство')], verbose_name='Важность')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
