# Generated by Django 5.0.4 on 2024-04-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('avatar', models.ImageField(upload_to='users/images/', verbose_name='Аватар пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Имэйл')),
                ('friend_code', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=150, verbose_name='Название заметки')),
                ('note_text', models.TextField(max_length=9999999, verbose_name='Текст заметки')),
                ('note_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('note_refresh_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения заметки')),
                ('completion_status_tag', models.CharField(choices=[('in_progress', 'Принято в работу'), ('completed', 'Завершено')])),
                ('importance_status_tag', models.CharField(choices=[('low', 'Может подождать'), ('medium', 'В порядке очереди'), ('high', 'Требуется немедленное вмешательство')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_main.user')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('administrator', 'Administrator')], default='member', max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_main.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_main.user')),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
