# Generated by Django 5.0.4 on 2024-04-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0001_initial'),
        ('users', '0003_group_creator_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.group', verbose_name='Группа'),
        ),
    ]
