# Generated by Django 5.0.4 on 2024-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='completion_status_tag',
            field=models.CharField(choices=[('in_progress', 'Принято в работу'), ('completed', 'Завершено')], verbose_name='Статус завершения'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='importance_status_tag',
            field=models.CharField(choices=[('low', 'Может подождать'), ('medium', 'В порядке очереди'), ('high', 'Требуется немедленное вмешательство')], verbose_name='Важность'),
        ),
    ]
