# Generated by Django 5.0.4 on 2024-04-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0004_alter_notes_user'),
        ('users', '0008_alter_group_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.group', verbose_name='Группа'),
        ),
    ]
