# Generated by Django 5.0.4 on 2024-04-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0004_alter_notes_completion_status_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_main.user', verbose_name='Автор'),
        ),
    ]
