# Generated by Django 5.0.4 on 2024-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0006_alter_group_group_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='completion_status_tag',
            field=models.CharField(choices=[('seen', 'Просмотрено'), ('in_progress', 'Принято в работу'), ('completed', 'Завершено')], null=True, verbose_name='Статус завершения'),
        ),
    ]
