# Generated by Django 5.0.4 on 2024-04-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0007_alter_notes_completion_status_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='importance_status_tag',
            field=models.CharField(blank=True, choices=[('low', 'Может подождать'), ('medium', 'В порядке очереди'), ('high', 'Требуется немедленное вмешательство')], verbose_name='Важность'),
        ),
    ]
