# Generated by Django 5.0.4 on 2024-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0008_alter_notes_group_alter_notes_importance_status_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
