# Generated by Django 5.0.4 on 2024-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_main', '0009_alter_notes_note_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='completion_status_tag',
            field=models.CharField(blank=True, choices=[('seen', 'Просмотрено'), ('in_progress', 'Принято в работу'), ('completed', 'Завершено')], null=True, verbose_name='Статус завершения'),
        ),
    ]
